/* Database schema to keep the structure of entire database. */

create table animals( id INT GENERATED BY DEFAULT AS IDENTITY, name VARCHAR(50), date_of_birth DATE,
escape_attempts INT, neutered BOOL, weight_kg DECIMAL);

ALTER TABLE animals ADD species varchar(30);

create table owners (
   id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   full_name VARCHAR(50),
   age INT
);

create table species (
   id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   name VARCHAR(50)
);

ALTER TABLE animals
  ADD CONSTRAINT pk
    PRIMARY KEY (id);

alter table animals
drop column species;

ALTER TABLE animals
ADD COLUMN species_id int REFERENCES species(id);

ALTER TABLE animals
ADD COLUMN owner_id int REFERENCES owners(id);

create table vets (
   id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   name VARCHAR(50),
   age INT,
   date_of_graduation DATE
);

create table specializations (
   vet_id INT,
   species_id INT
);

create table visits (
   vet_id INT,
   animal_id INT,
   visit_date DATE
);

ALTER TABLE owners ADD COLUMN email VARCHAR(120);

create index visits_animals ON visits(animal_id);

create index visits_vet_ids ON visits(vet_id);

create index owners_emails ON owners(email);

