/* Database schema to keep the structure of entire database. */

create table animals( id INT GENERATED BY DEFAULT AS IDENTITY, name VARCHAR(50), date_of_birth DATE,
escape_attempts INT, neutered BOOL, weight_kg DECIMAL);

ALTER TABLE animals ADD species varchar(30);

create table owners (
   id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   full_name VARCHAR(50),
   age INT
);

create table species (
   id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   name VARCHAR(50)
);

ALTER TABLE animals
  ADD CONSTRAINT pk
    PRIMARY KEY (id);

alter table animals
drop column species;

ALTER TABLE animals
ADD COLUMN species_id int REFERENCES species(id);

ALTER TABLE animals
ADD COLUMN owner_id int REFERENCES owners(id);