/* Database schema to keep the structure of entire database. */

create table animals( id INT GENERATED BY DEFAULT AS IDENTITY, name VARCHAR(50), date_of_birth DATE,
escape_attempts INT, neutered BOOL, weight_kg DECIMAL);

ALTER TABLE animals ADD species varchar(30);
